### ISSUE TITLE
no help message or man page

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/provami#1]
no documentation for provami

provami-qt --help
QMetaObject::connectSlotsByName: No matching signal for on_stats_changed()
terminate called after throwing an instance of 'wreport::error_consistency'
  what():  unsupported url "--help"
Annullato (core dumped)

 man provami-qt
Non c'è il manuale per provami-qt

**Comment by spanezz** [comment]
I have now added --help, --version and a simple man page.
The man page is also now installed on make install (2a326c824bb8786f0de7406aef76f5bb6acdd986)
