### ISSUE TITLE
scorciatoia per il refresh

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/provami#11]
presentare all'utente la scorciatoia per il refresh (ctrl-r)
viene richiamato spessissimo e usare il mouse è molto scomodo

**Comment by pat1** [comment]
ho trovato ctrl-r nel menu "File"

**Comment by spanezz** [comment]
Ctrl+R da me sembra funzionare: se è sufficiente come visibilità che sia evidenziato nel menu File, chiudiamo questo bug?
