### ISSUE TITLE
limit: possibilità di selezionare unlimited

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/provami#12]
il valore "Limit" deve essere sempre presente (vuoto non ha significato)
per visualizzare tutto bisogna mettere un numero molto grande  che se pur funziona non è molto ergonomico

suggerirei di rendere efficace un valore di limit vuoto o implementare un bottone unlimit

**Comment by spanezz** [comment]
Confermo, è un bug che se il campo limit è vuoto non venga al momento selezionato nessun risultato, invece di selezionare tutti i risultati.

**Comment by spanezz** [comment]
Done in b8b654f83552c29d072163f3dc947b8a4925fbf8
