### ISSUE TITLE
tab query: significato di copypaste

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/provami#13]
- cosa significa copypaste ?
- provo a inserire come Key B12101 e Value 273.15 ma all'invio vengono sistematicamente eliminati (campi vuoti)
- come faccio una query sugli attributi ? e sui dati di anagrafica?

**Comment by spanezz** [comment]
Rispondo a "cosa significa copypaste?" e apro bug separati per gli altri due punti.

Copypaste è una riga che si può copiare e incollare in una riga di comando (per esempio di dbadb), con tanto di escaping di parametri che contengono apici e spazi. L'idea è poter usare provami per costruire interattivamente delle query, e poi riusare facilmente quelle query, per esempio, in script operativi.
Cambio "Copypaste" in "Shell query"?
