### ISSUE TITLE
map: il fattore di zoom viene resettato ad ogni selezione di stazione

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/provami#15]
Nel tab Map il fattore di zoom viene resettato ad ogni selezione di stazione rendendp alquanto difficontoso il cambio di stazione selezionata dovendo rizummare ogni volta.

**Comment by spanezz** [comment]
Confermo: cliccando su una singola stazione, la stazione viene selezionata e lo zoom viene resettato mostrando il mondo intero.

Cliccare su una stazione per selezionarla non deve cambiare il livello di zoom.

**Comment by spanezz** [comment]
Fatto in f5bad998b6ab990ff598dfb81dafd97c23f85aa8
