### ISSUE TITLE
results: Larghezza colonne nella tabella dati costante per tutte le colonne

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/provami#16]
Alcune colonne della tabella dati richiedono SEMPRE un resize per essere visualizzate (date, level).
Operazione noisa.

**Comment by spanezz** [comment]
Mi puoi fare uno screenshot delle colonne prima del resize?

**Comment by pat1** [comment]
farò lo screenshot ma sono  date e level che non stanno dentro lo spazio disponibile

**Comment by pat1** [comment]
![schermata da 2015-12-02 19 36 55](https://cloud.githubusercontent.com/assets/3214854/11540288/38db121e-992c-11e5-88ce-42ff959fa7d9.png)
come si può notare tutte le volte slarga, allarga e tira e sposta
se si apre provami una decina di volte è un po' snervante

**Comment by brancomat** [comment]
Sugli enhancement lo sviluppo su "provami" è fermo in favore di https://github.com/ARPA-SIMC/dballe-web/

Questo problema in particolare su `dballe-web` non mi sembra sia presente, la chiudo, nel caso riaprila di là.
