### ISSUE TITLE
map: allow to select any station, not just the ones in the current result set

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/provami#17]
per riprodurre:
selezione di una stazione nel tab Map
refresh
la selezione di una stazione differente risulta impossibile

collegato a #9 e #10

**Comment by spanezz** [comment]
Confermo: le uniche stazioni selezionabili sono quelle accettate dal filtro attivo nell'ultimo refresh, mentre dovrebbero essere selezionabili, o tutte le stazioni, o tutte le stazioni che hanno dati che corrispondono alla parte del filtro corrente che non riguarda le stazioni.

**Comment by spanezz** [comment]
Fatto in e42dfd4be530b476fa732e6be829c0155119a15e
