### ISSUE TITLE
Tab query: i codici variabile non sono riconosciuti come chiavi valide

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/provami#18]
provo a inserire come Key B12101 e Value 273.15 ma all'invio vengono sistematicamente eliminati (campi vuoti)

(split from #13)

**Comment by spanezz** [comment]
Se da linea di comando fai `dbadb export B12101=273.15` funziona?

**Comment by pat1** [comment]
duplicated of #19

**Comment by pat1** [comment]
credo sia chiusa insieme alla #19
