### ISSUE TITLE
Tab query: come faccio una query sugli attributi ? e sui dati di anagrafica?

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/provami#19]
(split from #13)

**Comment by spanezz** [comment]
Il tab Query prende come chiavi "ana_filter", "data_filter" e "attr_filter": funzionano?

**Comment by pat1** [comment]
a saperlo si ...

**Comment by pat1** [comment]
non si possono "tendinare" le 3 scelte o avere qualche testo di help?

**Comment by spanezz** [comment]
Dovrebbero funzionare tutte le chiavi documentate nella documentazione per l'API fortran. Posso provare a cambiare il campo con un combo box con sotto tutte le opzioni

**Comment by spanezz** [comment]
Implementata la selezione del campo con un combo box.
