### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/provami#2]
provami-qt sqlite:///scratch/ppatruno/arpa-meteonetwork/temperatura/temperatura.sqlite
QMetaObject::connectSlotsByName: No matching signal for on_stats_changed()
progress  "data" : new task:  "Loading data..."
progress  "summary" : new task:  "Loading summary..."
progress  "summary" : task update:  "Loading initial summary from db..."
Errore di segmentazione (core dumped)

**Comment by pat1** [comment]
la macchina è pigna
il DB
/scratch/ppatruno/arpa-meteonetwork/temperatura/temperatura.sqlite
uso la versione installata
rpm -q provami-qt
provami-qt-1.0.0-4828.fc20.x86_64
il comando è
 provami-qt sqlite:///scratch/ppatruno/arpa-meteonetwork/temperatura/temperatura.sqlite

**Comment by spanezz** [comment]
Fixed in branch devel.

**Comment by brancomat** [comment]
packaged in 1.0.0-4831
