### ISSUE TITLE
le esportazioni riportano sempre errore

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/provami#22]
ripporta:
ERROR: this command requires the dballe python module to run

ma python-dballe è installato
rpm -q python-dballe
python-dballe-7.6-1.fc20

**Comment by spanezz** [comment]
Ti chiedo aiuto a cercare di riprodurre il problema con dbaexport.

Se lanci provami da terminale e fai una esportazione, dovresti vedere nel terminale una riga tipo questa:

`Running dbaexport ("--dsn", "sqlite:db.sqlite", "--outfile", "output.bufr", "bufr")`

Me la puoi incollare qui, e poi provare a lanciare dbaexport con gli stessi parametri?

Quando lo faccio io sul mio sistema, dbaexport trova il modulo python di dballe.

**Comment by spanezz** [comment]
L'ho chiuso per sbaglio, riapro.

**Comment by brancomat** [comment]
Trovato l'inghippo: il test su dbaexport è legato ad un "import dballe" ma in realtà si porta dietro l'import di wreport (modulo python che non era presente).
E' un bug del modulo python di dballe? O dei file di pacchettizzazione che devono esplicitare la dipendenza?

**Comment by spanezz** [comment]
Dei file di pacchettizzazione: il modulo python di dballe deve dipendere dal modulo python di wreport.

**Comment by brancomat** [comment]
Fixed in https://github.com/ARPA-SIMC/dballe/commit/872019e244a1c077bff8a217b7a927308afd385a
