### ISSUE TITLE
fault nella selezione stazione

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/provami#23]
sulla mappa
mouse di destra "reload" (che non sappiamo cosa voglia dire)
"refresh" obbligatorio per vedere le stazioni
selezionare con mouse una stazione
non funziona e si ottiene:
"file:///usr/share/provami/mapview/index.html:179: TypeError: undefined is not an object (evaluating 'window.provami.js_station_selected')"

**Comment by spanezz** [comment]
"reload" è una funzionalità che è lí di default come conseguenza del fatto che la mappa è implementata come una pagina web dentro a un mini web browser. Fare un reload della pagina della mappa incasina tutto, perché manda fuori sincrono l'idea delle stazioni che ha la pagina della mappa con l'idea delle stazioni che ha provami.

Ora guardo di far sparire il menu tasto destro dalla mappa.

Avevate un motivo per provare a fare reload?
