### ISSUE TITLE
introduce explicit versioning (and maybe push version to 7.7)

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/provami#24]
Now the version is always 1.0.0
This could avoid conflicts with the old "provami", explicit the succession and lead back fedora specfile to the "provami" namespace
(Related to https://github.com/ARPA-SIMC/dballe/issues/24)

**Comment by spanezz** [comment]
I added a variable for the version number in CMakeLists.txt, which makes its way into provami-qt --version. Feel free to change it with what you need.

Does this solve your problem?

**Comment by brancomat** [comment]
perfect
