### ISSUE TITLE
refresh iniziale

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/provami#3]
All'attivazione bisogna sempre fare un refresh.
Parrebbe una operazione superflua.

**Comment by spanezz** [comment]
In realtà lo fa lui da solo. Se però il database è molto grosso ci vuole tempo, e dall'interfaccia sembra che non ci siano dati.

Serve magari avere un progress reporting piú visibile.

**Comment by pat1** [comment]
nel mio ambiente il refresh iniziale proprio non funziona; è sempre necessario un refresh iniziale per visualizzare i dati.

**Comment by spanezz** [comment]
Appena compare la finestra, nella barra in basso proprio nel bordo inferiore della finestra, dice "Loading data... Loading summary from db..." o è vuota?

**Comment by spanezz** [comment]
Una cosa che ho notato, caricando un database piccolo, è che alla partenza compaiono i dati, ma appena ridimensiono la finestra scompaiono finché non rifaccio un refresh.

**Comment by spanezz** [comment]
Fatto in 828bf1dd62623a246787a952673c7ba2fddf037b
