### ISSUE TITLE
selzione del dato

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/provami#4]
nella tabella dei dati la selezione del dato (e dei suoi attributi) avviene solamente con un click del mouse.
La selezione effettuata muovendosi con le frecce non funziona.
questo rende la possibilità di scorrere i dati e quindi gli attributi estremamente inefficiente

**Comment by spanezz** [comment]
Confermo; serve aggiornare le tabelle nei tab stazione e attributi ogni volta che cambia la riga corrente nella tabella dei dati.

**Comment by spanezz** [comment]
Done in 2f4f7c17c6cf688ee2437b018f1118871d06ae64
