### ISSUE TITLE
Make the result summary more readable

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/provami#5]
le finestre della data minima e massima non presentano i valori corrispondenti alla selezione.

**Comment by pat1** [comment]
mi pare di aver capito che gli estremi della data sono presentati come summary sopra la finestra dati

**Comment by spanezz** [comment]
Sono al momento presentati solo come tooltip.

Credo ci sia abbastanza spazio nel tab "1 Filter" per visualizzare due o tre righe di summary sui dati. Provo a implementarlo.

**Comment by spanezz** [comment]
Ho appena notato adesso che a sinistra del campo di input del "Limit", compare "Summary:" seguito da data minima e massima, e numero di elementi. È giusto come hai detto tu, come summary sopra la finestra dei dati. Le date in formato ISO sono cosí poco leggibili che non le notavo nemmeno.
Una riga di summary è molto stretta per farci stare due date, e mi piacerebbe poter dire tipo "Minimum date, Maximum date, Number of results". Provo a spostare nel tab "Filter", anche se poi comparirebbe solo quando il tab è attivo?

**Comment by pat1** [comment]
bho, se non c'è una soluzione migliore lasciamo così

**Comment by spanezz** [comment]
Non ho capito: sposto il summary nel tab "Filter", o lascio cosí?

**Comment by spanezz** [comment]
Intanto ho tolto la T dalle date e l'ho riformulato un po'

**Comment by pat1** [comment]
per ora lasciamo così
