### ISSUE TITLE
usabilità: alcune finestre invece di soli tab

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/provami#7]
avere la finestra della mappa separata invece che in un tab renderebbe l'app molto più usabile

**Comment by spanezz** [comment]
Possibile idea di implementazione:
https://forum.qt.io/topic/38631/dragging-a-tab-from-qtabwidget-into-a-separate-window/5

**Comment by pat1** [comment]
ottima soluzione

**Comment by spanezz** [comment]
Ora cliccando col tasto destro sulla linguetta di un tab compare un menu che offre di spostare il tab in un'altra finestra. All'uscita, provami si ricorda il numero di finestre e quali tab sono in quali finestre, cosí non c'è bisogno di riorganizzare tutto ogni volta che lo si usa.
