### ISSUE TITLE
results: modifica dei valori

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/provami#8]
la modifica e estremamente difficoltosa:
dopo doppio click sul valore in tabella da modificare
è come se ci fossere due caselle una sopra l'altra
una col numero preesistente bianco su fondo blu
e una in cui scrivo nero su fondo trasparente

**Comment by spanezz** [comment]
Questo non riesco a riprodurlo da me. Che versione hai delle librerie Qt?

**Comment by spanezz** [comment]
Intanto in e5205528918726584e0bd746981afe23134a63ab ho aggiunto la possibilità di editare un elemento anche con un singolo click sulla cella corrente. Ho anche investigato come editare mentre ci si muove da tastiera, e Qt attiva l'editing se si preme F2.

Volendo, si può dirgli di iniziare l'edit alla pressione di qualunque tasto. Questo significherebbe che se vai sulla cella di un valore e scrivi "42", lo modifichi subito senza dover esplicitamente entrare in editing. Mi sembra una cosa comoda, ma chiedo conferma a te prima di attivarla.

**Comment by spanezz** [comment]
Scusa, l'ho chiuso per sbaglio

**Comment by pat1** [comment]
Fedora 20 con qt-4.8.6-30.fc20
http://koji.fedoraproject.org/koji/buildinfo?buildID=635055

**Comment by pat1** [comment]
io non esagerei nella facilità di modifica del dato per evitare modifiche indesiderate.
Mi concentrerei sull'oggetto del bug:
è come se ci fossere due caselle una sopra l'altra
una col numero preesistente bianco su fondo blu
e una in cui scrivo nero su fondo trasparente

**Comment by spanezz** [comment]
Puoi riprovare con un provami che contiene la patch 828bf1dd62623a246787a952673c7ba2fddf037b ?

**Comment by pat1** [comment]
il problema persite

**Comment by brancomat** [comment]
non riesco a riprodurre l'errore con le ultime versioni, chiudo il bug
