### ISSUE TITLE
nel tab Map manca un "seleziona niente"

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/provami#9]

**Comment by spanezz** [comment]
Il tab della mappa è già abbastanza pieno e non riesco a vedere un posto decente dove mettere un bottone "seleziona niente". Come prima cosa, meglio di niente, posso aggiungo un menú "Select" e mettere lí la funzione "Clear station selection".

**Comment by spanezz** [comment]
Done in 77cd6c2e42dd24e839169da3809c67347ab218f5
